-- File: init.sql

-- 1. Create profiles table
CREATE TABLE public.profiles (
  id UUID NOT NULL,
  username TEXT NULL,
  first_name TEXT NULL,
  last_name TEXT NULL,
  avatar_url TEXT NULL,
  created_at TIMESTAMPTZ NULL DEFAULT timezone('utc', now()),
  customer_id TEXT NULL,
  email TEXT NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- 2. Create cv_profiles table
CREATE TABLE public.cv_profiles (
  id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id UUID NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NULL,
  website TEXT NULL,
  linkedin TEXT NULL,
  github TEXT NULL,
  address TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cv_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT cv_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- 3. Function for on_auth_user_created (legacy)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$;

-- 4. Trigger for handle_new_user()
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. Function for extended signup
CREATE OR REPLACE FUNCTION public.handle_new_user_signup()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  display_name TEXT;
  first_name TEXT;
  last_name TEXT;
BEGIN
  display_name := NEW.raw_user_meta_data->>'full_name';

  IF display_name IS NOT NULL THEN
    first_name := split_part(display_name, ' ', 1);
    IF strpos(display_name, ' ') > 0 THEN
      last_name := ltrim(substr(display_name, strpos(display_name, ' ') + 1));
    ELSE
      last_name := NULL;
    END IF;
  ELSE
    first_name := NULL;
    last_name := NULL;
  END IF;

  -- Insert into profiles with enhanced fields
  INSERT INTO public.profiles (id, username, avatar_url, first_name, last_name, email)
  VALUES (
    NEW.id,
    display_name,
    NEW.raw_user_meta_data->>'avatar_url',
    first_name,
    last_name,
    NEW.email
  );

  -- Insert into cv_profiles
  IF NEW.email IS NOT NULL OR display_name IS NOT NULL THEN
    INSERT INTO public.cv_profiles (user_id, email, first_name, last_name)
    VALUES (NEW.id, NEW.email, first_name, last_name);
  END IF;

  RETURN NEW;
END;
$$;

-- 6. Trigger for extended signup
CREATE TRIGGER on_auth_user_signup
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_signup();

-- 7. Plans, Prices, Subscriptions, Keep Alive, Emails, CoverLetters, CVs
CREATE TABLE public.plans (
  id TEXT NOT NULL DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMPTZ NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NULL DEFAULT now(),
  CONSTRAINT plans_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.prices (
  id TEXT NOT NULL DEFAULT gen_random_uuid(),
  plan_id TEXT NULL,
  amount INTEGER NOT NULL,
  currency TEXT NOT NULL,
  interval TEXT NOT NULL,
  created_at TIMESTAMPTZ NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NULL DEFAULT now(),
  CONSTRAINT prices_pkey PRIMARY KEY (id),
  CONSTRAINT prices_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans (id)
) TABLESPACE pg_default;

CREATE TABLE public.subscriptions (
  id TEXT NOT NULL DEFAULT gen_random_uuid(),
  user_id UUID NULL,
  plan_id TEXT NULL,
  price_id TEXT NULL,
  interval TEXT NOT NULL,
  status TEXT NOT NULL,
  current_period_start TIMESTAMPTZ NULL,
  current_period_end TIMESTAMPTZ NULL,
  cancel_at_period_end BOOLEAN NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NULL DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_key UNIQUE (user_id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans (id),
  CONSTRAINT subscriptions_price_id_fkey FOREIGN KEY (price_id) REFERENCES public.prices (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.keep_alive (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name TEXT NULL DEFAULT ''::text,
  random TEXT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT keep_alive_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.emails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  email TEXT NULL,
  CONSTRAINT emails_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.cover_letters (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  company TEXT,
  position TEXT,
  status TEXT CHECK (status IN ('draft', 'published', 'archived')) DEFAULT 'draft',
  version INTEGER DEFAULT 1,
  template_id UUID
) TABLESPACE pg_default;

CREATE TABLE public.cvs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  title TEXT NOT NULL,
  summary TEXT,
  education JSONB,
  experience JSONB,
  skills JSONB,
  projects JSONB,
  certifications JSONB,
  languages JSONB,
  interests JSONB,
  status TEXT CHECK (status IN ('draft', 'published', 'archived')) DEFAULT 'draft',
  version INTEGER DEFAULT 1,
  template_id UUID
) TABLESPACE pg_default;
