import { Briefcase, GraduationCap, Pen } from "lucide-react";

export const AI_PROVIDERS = {
	deepseek: {
		id: "deepseek",
		displayName: "DeepSeek",
		proOnly: false,
		modelIds: ["deepseek-chat"],
		defaultModelId: "deepseek-chat",
	},
	openai: {
		id: "openai",
		displayName: "OpenAI",
		proOnly: true,
		modelIds: ["gpt-4o", "gpt-4o-mini"],
		defaultModelId: "gpt-4o",
	},
};

export const RECOMMENDED_MODEL = AI_PROVIDERS.deepseek.defaultModelId;

export type AIProvider = keyof typeof AI_PROVIDERS;

export const GENERATION_LANGUAGES = [
	{ value: "english", label: "English" },
	{ value: "spanish", label: "Spanish" },
	{ value: "french", label: "French" },
	{ value: "german", label: "German" },
	{ value: "italian", label: "Italian" },
	{ value: "portuguese", label: "Portuguese" },
	{ value: "dutch", label: "Dutch" },
	{ value: "swedish", label: "Swedish" },
	{ value: "norwegian", label: "Norwegian" },
	{ value: "danish", label: "Danish" },
	{ value: "finnish", label: "Finnish" },
	{ value: "polish", label: "Polish" },
	{ value: "czech", label: "Czech" },
	{ value: "hungarian", label: "Hungarian" },
	{ value: "romanian", label: "Romanian" },
	{ value: "bulgarian", label: "Bulgarian" },
	{ value: "croatian", label: "Croatian" },
	{ value: "serbian", label: "Serbian" },
	{ value: "slovenian", label: "Slovenian" },
	{ value: "slovak", label: "Slovak" },
	{ value: "lithuanian", label: "Lithuanian" },
	{ value: "latvian", label: "Latvian" },
	{ value: "estonian", label: "Estonian" },
	{ value: "russian", label: "Russian" },
	{ value: "ukrainian", label: "Ukrainian" },
	{ value: "belarusian", label: "Belarusian" },
	{ value: "georgian", label: "Georgian" },
	{ value: "armenian", label: "Armenian" },
	{ value: "azerbaijani", label: "Azerbaijani" },
	{ value: "kazakh", label: "Kazakh" },
	{ value: "uzbek", label: "Uzbek" },
	{ value: "turkmen", label: "Turkmen" },
	{ value: "kyrgyz", label: "Kyrgyz" },
	{ value: "tajik", label: "Tajik" },
	{ value: "mongolian", label: "Mongolian" },
	{ value: "chinese", label: "Chinese" },
	{ value: "japanese", label: "Japanese" },
	{ value: "korean", label: "Korean" },
	{ value: "vietnamese", label: "Vietnamese" },
	{ value: "thai", label: "Thai" },
	{ value: "lao", label: "Lao" },
	{ value: "cambodian", label: "Cambodian" },
	{ value: "burmese", label: "Burmese" },
	{ value: "malay", label: "Malay" },
	{ value: "indonesian", label: "Indonesian" },
	{ value: "filipino", label: "Filipino" },
	{ value: "hindi", label: "Hindi" },
	{ value: "bengali", label: "Bengali" },
	{ value: "urdu", label: "Urdu" },
	{ value: "punjabi", label: "Punjabi" },
	{ value: "gujarati", label: "Gujarati" },
	{ value: "marathi", label: "Marathi" },
	{ value: "tamil", label: "Tamil" },
	{ value: "telugu", label: "Telugu" },
	{ value: "kannada", label: "Kannada" },
	{ value: "malayalam", label: "Malayalam" },
	{ value: "sinhala", label: "Sinhala" },
	{ value: "nepali", label: "Nepali" },
	{ value: "tibetan", label: "Tibetan" },
	{ value: "arabic", label: "Arabic" },
	{ value: "hebrew", label: "Hebrew" },
	{ value: "persian", label: "Persian" },
	{ value: "turkish", label: "Turkish" },
	{ value: "greek", label: "Greek" },
	{ value: "albanian", label: "Albanian" },
	{ value: "macedonian", label: "Macedonian" },
	{ value: "bosnian", label: "Bosnian" },
	{ value: "montenegrin", label: "Montenegrin" },
	{ value: "icelandic", label: "Icelandic" },
	{ value: "faroese", label: "Faroese" },
	{ value: "maltese", label: "Maltese" },
	{ value: "welsh", label: "Welsh" },
	{ value: "irish", label: "Irish" },
	{ value: "scottish_gaelic", label: "Scottish Gaelic" },
	{ value: "breton", label: "Breton" },
	{ value: "cornish", label: "Cornish" },
	{ value: "manx", label: "Manx" },
	{ value: "basque", label: "Basque" },
	{ value: "catalan", label: "Catalan" },
	{ value: "galician", label: "Galician" },
	{ value: "occitan", label: "Occitan" },
	{ value: "frisian", label: "Frisian" },
	{ value: "luxembourgish", label: "Luxembourgish" },
	{ value: "swahili", label: "Swahili" },
	{ value: "yoruba", label: "Yoruba" },
	{ value: "igbo", label: "Igbo" },
	{ value: "hausa", label: "Hausa" },
	{ value: "amharic", label: "Amharic" },
	{ value: "somali", label: "Somali" },
	{ value: "oromo", label: "Oromo" },
	{ value: "zulu", label: "Zulu" },
	{ value: "xhosa", label: "Xhosa" },
	{ value: "tswana", label: "Tswana" },
	{ value: "sesotho", label: "Sesotho" },
	{ value: "shona", label: "Shona" },
	{ value: "chichewa", label: "Chichewa" },
	{ value: "luganda", label: "Luganda" },
	{ value: "kinyarwanda", label: "Kinyarwanda" },
	{ value: "kirundi", label: "Kirundi" },
	{ value: "tigrinya", label: "Tigrinya" },
	{ value: "tigre", label: "Tigre" },
	{ value: "afar", label: "Afar" },
	{ value: "dinka", label: "Dinka" },
	{ value: "nuer", label: "Nuer" },
	{ value: "acholi", label: "Acholi" },
	{ value: "lugbara", label: "Lugbara" },
	{ value: "runyankole", label: "Runyankole" },
	{ value: "runyoro", label: "Runyoro" },
	{ value: "rutooro", label: "Rutooro" },
	{ value: "rukiga", label: "Rukiga" },
] as const;

export const DEFAULT_LANGUAGE = "english";

export const TONES = [
	{
		value: "professional",
		label: "Professional",
		description: "Formal language suitable for corporate environments",
		icon: Briefcase,
		example: "Experienced software engineer with expertise in React and TypeScript...",
	},
	{
		value: "academic",
		label: "Academic",
		description: "Scholarly tone ideal for research and education",
		icon: GraduationCap,
		example: "Research-focused software engineer specializing in the implementation of React frameworks...",
	},
	{
		value: "creative",
		label: "Creative",
		description: "Engaging style that showcases personality",
		icon: Pen,
		example: "Passionate coder who loves bringing ideas to life through React and TypeScript...",
	},
] as const;

export const RECOMMENDED_TONE = "professional";
