// Generated by React Router

import "react-router";

declare module "react-router" {
	interface Register {
		pages: Pages;
		routeFiles: RouteFiles;
	}
}

type Pages = {
	"/": {
		params: {};
	};
	"/pricing": {
		params: {};
	};
	"/updates": {
		params: {};
	};
	"/terms-of-service": {
		params: {};
	};
	"/privacy-policy": {
		params: {};
	};
	"/signin": {
		params: {};
	};
	"/signup": {
		params: {};
	};
	"/forgot-password": {
		params: {};
	};
	"/update-password": {
		params: {};
	};
	"/signout": {
		params: {};
	};
	"/dashboard": {
		params: {};
	};
	"/documents": {
		params: {};
	};
	"/documents/cvs": {
		params: {};
	};
	"/documents/cvs/:id": {
		params: {
			id: string;
		};
	};
	"/documents/cover-letters": {
		params: {};
	};
	"/documents/profile": {
		params: {};
	};
	"/account": {
		params: {};
	};
	"/account/billing": {
		params: {};
	};
	"/account/settings": {
		params: {};
	};
	"/api/auth/confirm": {
		params: {};
	};
	"/api/confirm-signup-otp": {
		params: {};
	};
	"/api/cv/generate": {
		params: {};
	};
	"/api/cv/pdf-latex": {
		params: {};
	};
	"/api/keep-alive": {
		params: {};
	};
	"/api/mailing-list": {
		params: {};
	};
	"/api/webhook": {
		params: {};
	};
	"/healthcheck": {
		params: {};
	};
	"/resources/theme-toggle": {
		params: {};
	};
};

type RouteFiles = {
	"root.tsx": {
		id: "root";
		page:
			| "/"
			| "/pricing"
			| "/updates"
			| "/terms-of-service"
			| "/privacy-policy"
			| "/signin"
			| "/signup"
			| "/forgot-password"
			| "/update-password"
			| "/signout"
			| "/dashboard"
			| "/documents"
			| "/documents/cvs"
			| "/documents/cvs/:id"
			| "/documents/cover-letters"
			| "/documents/profile"
			| "/account"
			| "/account/billing"
			| "/account/settings"
			| "/api/auth/confirm"
			| "/api/confirm-signup-otp"
			| "/api/cv/generate"
			| "/api/cv/pdf-latex"
			| "/api/keep-alive"
			| "/api/mailing-list"
			| "/api/webhook"
			| "/healthcheck"
			| "/resources/theme-toggle";
	};
	"routes/_landing.tsx": {
		id: "landing";
		page: "/" | "/pricing" | "/updates" | "/terms-of-service" | "/privacy-policy";
	};
	"routes/_landing._index.tsx": {
		id: "landing-index";
		page: "/";
	};
	"routes/_landing.pricing.tsx": {
		id: "landing-pricing";
		page: "/pricing";
	};
	"routes/_landing.updates.tsx": {
		id: "landing-updates";
		page: "/updates";
	};
	"routes/_landing.terms-of-service.tsx": {
		id: "landing-terms";
		page: "/terms-of-service";
	};
	"routes/_landing.privacy-policy.tsx": {
		id: "landing-privacy";
		page: "/privacy-policy";
	};
	"routes/_auth.tsx": {
		id: "auth";
		page: "/" | "/signin" | "/signup" | "/forgot-password" | "/update-password" | "/signout";
	};
	"routes/_auth.signin.tsx": {
		id: "auth-signin";
		page: "/signin";
	};
	"routes/_auth.signup.tsx": {
		id: "auth-signup";
		page: "/signup";
	};
	"routes/_auth.forgot-password.tsx": {
		id: "auth-forgot-password";
		page: "/forgot-password";
	};
	"routes/_auth.update-password.tsx": {
		id: "auth-update-password";
		page: "/update-password";
	};
	"routes/_auth.signout.tsx": {
		id: "auth-signout";
		page: "/signout";
	};
	"routes/_app.tsx": {
		id: "app";
		page:
			| "/"
			| "/dashboard"
			| "/documents"
			| "/documents/cvs"
			| "/documents/cvs/:id"
			| "/documents/cover-letters"
			| "/documents/profile"
			| "/account"
			| "/account/billing"
			| "/account/settings";
	};
	"routes/_app.dashboard.tsx": {
		id: "app-dashboard";
		page: "/dashboard";
	};
	"routes/_app._documents.tsx": {
		id: "app-documents";
		page:
			| "/documents"
			| "/documents/cvs"
			| "/documents/cvs/:id"
			| "/documents/cover-letters"
			| "/documents/profile";
	};
	"components/layout/pathless-layout.tsx": {
		id: "app-documents-cvs";
		page: "/documents/cvs" | "/documents/cvs/:id";
	};
	"routes/_app._documents.cvs._index.tsx": {
		id: "app-documents-cvs-index";
		page: "/documents/cvs";
	};
	"routes/_app._documents.cvs.$id.tsx": {
		id: "app-documents-cvs-id";
		page: "/documents/cvs/:id";
	};
	"routes/_app._documents.cover-letters.tsx": {
		id: "app-documents-cover-letters";
		page: "/documents/cover-letters";
	};
	"routes/_app._documents.profile.tsx": {
		id: "app-documents-profile";
		page: "/documents/profile";
	};
	"routes/_app.account.tsx": {
		id: "app-account";
		page: "/account" | "/account/billing" | "/account/settings";
	};
	"routes/_app.account._index.tsx": {
		id: "app-account-index";
		page: "/account";
	};
	"routes/_app.account.billing.tsx": {
		id: "app-account-billing";
		page: "/account/billing";
	};
	"routes/_app.account.settings.tsx": {
		id: "app-account-settings";
		page: "/account/settings";
	};
	"routes/api.auth.confirm.ts": {
		id: "api-auth-confirm";
		page: "/api/auth/confirm";
	};
	"routes/api.confirm-signup-otp.ts": {
		id: "api-confirm-signup-otp";
		page: "/api/confirm-signup-otp";
	};
	"routes/api.cv.generate.ts": {
		id: "api-cv-generate";
		page: "/api/cv/generate";
	};
	"routes/api.cv.pdf-latex.ts": {
		id: "api-cv-pdf-latex";
		page: "/api/cv/pdf-latex";
	};
	"routes/api.keep-alive.ts": {
		id: "api-keep-alive";
		page: "/api/keep-alive";
	};
	"routes/api.mailing-list.ts": {
		id: "api-mailing-list";
		page: "/api/mailing-list";
	};
	"routes/api.webhook.ts": {
		id: "api-webhook";
		page: "/api/webhook";
	};
	"routes/healthcheck.ts": {
		id: "healthcheck";
		page: "/healthcheck";
	};
	"routes/resources.theme-toggle.tsx": {
		id: "resources-theme-toggle";
		page: "/resources/theme-toggle";
	};
};
