// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/confirm-signup-otp": {
    params: {};
  };
  "/resources/theme-toggle": {
    params: {};
  };
  "/api/auth/confirm": {
    params: {};
  };
  "/api/cv/pdf-latex": {
    params: {};
  };
  "/api/mailing-list": {
    params: {};
  };
  "/api/cv/generate": {
    params: {};
  };
  "/api/keep-alive": {
    params: {};
  };
  "/api/webhook": {
    params: {};
  };
  "/healthcheck": {
    params: {};
  };
  "/terms-of-service": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/updates": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/update-password": {
    params: {};
  };
  "/signout": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/cover-letters": {
    params: {};
  };
  "/cvs": {
    params: {};
  };
  "/cvs/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/settings": {
    params: {};
  };
  "/account/billing": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/confirm-signup-otp" | "/resources/theme-toggle" | "/api/auth/confirm" | "/api/cv/pdf-latex" | "/api/mailing-list" | "/api/cv/generate" | "/api/keep-alive" | "/api/webhook" | "/healthcheck" | "/terms-of-service" | "/privacy-policy" | "/pricing" | "/updates" | "/forgot-password" | "/update-password" | "/signout" | "/signin" | "/signup" | "/cover-letters" | "/cvs" | "/cvs/:id" | "/profile" | "/dashboard" | "/account" | "/account/settings" | "/account/billing";
  };
  "routes/api.confirm-signup-otp.ts": {
    id: "routes/api.confirm-signup-otp";
    page: "/api/confirm-signup-otp";
  };
  "routes/resources.theme-toggle.tsx": {
    id: "routes/resources.theme-toggle";
    page: "/resources/theme-toggle";
  };
  "routes/api.auth.confirm.ts": {
    id: "routes/api.auth.confirm";
    page: "/api/auth/confirm";
  };
  "routes/api.cv.pdf-latex.ts": {
    id: "routes/api.cv.pdf-latex";
    page: "/api/cv/pdf-latex";
  };
  "routes/api.mailing-list.ts": {
    id: "routes/api.mailing-list";
    page: "/api/mailing-list";
  };
  "routes/api.cv.generate.ts": {
    id: "routes/api.cv.generate";
    page: "/api/cv/generate";
  };
  "routes/api.keep-alive.ts": {
    id: "routes/api.keep-alive";
    page: "/api/keep-alive";
  };
  "routes/api.webhook.ts": {
    id: "routes/api.webhook";
    page: "/api/webhook";
  };
  "routes/healthcheck.ts": {
    id: "routes/healthcheck";
    page: "/healthcheck";
  };
  "routes/_landing.tsx": {
    id: "routes/_landing";
    page: "/terms-of-service" | "/privacy-policy" | "/pricing" | "/updates" | "/";
  };
  "routes/_landing.terms-of-service.tsx": {
    id: "routes/_landing.terms-of-service";
    page: "/terms-of-service";
  };
  "routes/_landing.privacy-policy.tsx": {
    id: "routes/_landing.privacy-policy";
    page: "/privacy-policy";
  };
  "routes/_landing.pricing.tsx": {
    id: "routes/_landing.pricing";
    page: "/pricing";
  };
  "routes/_landing.updates.tsx": {
    id: "routes/_landing.updates";
    page: "/updates";
  };
  "routes/_landing._index.tsx": {
    id: "routes/_landing._index";
    page: "/";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/forgot-password" | "/update-password" | "/signout" | "/signin" | "/signup";
  };
  "routes/_auth.forgot-password.tsx": {
    id: "routes/_auth.forgot-password";
    page: "/forgot-password";
  };
  "routes/_auth.update-password.tsx": {
    id: "routes/_auth.update-password";
    page: "/update-password";
  };
  "routes/_auth.signout.tsx": {
    id: "routes/_auth.signout";
    page: "/signout";
  };
  "routes/_auth.signin.tsx": {
    id: "routes/_auth.signin";
    page: "/signin";
  };
  "routes/_auth.signup.tsx": {
    id: "routes/_auth.signup";
    page: "/signup";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/cover-letters" | "/cvs" | "/cvs/:id" | "/profile" | "/dashboard" | "/account" | "/account/settings" | "/account/billing";
  };
  "routes/_app._documents.tsx": {
    id: "routes/_app._documents";
    page: "/cover-letters" | "/cvs" | "/cvs/:id" | "/profile";
  };
  "routes/_app._documents.cover-letters.tsx": {
    id: "routes/_app._documents.cover-letters";
    page: "/cover-letters";
  };
  "routes/_app._documents.cvs._index.tsx": {
    id: "routes/_app._documents.cvs._index";
    page: "/cvs";
  };
  "routes/_app._documents.cvs.$id.tsx": {
    id: "routes/_app._documents.cvs.$id";
    page: "/cvs/:id";
  };
  "routes/_app._documents.profile.tsx": {
    id: "routes/_app._documents.profile";
    page: "/profile";
  };
  "routes/_app.dashboard.tsx": {
    id: "routes/_app.dashboard";
    page: "/dashboard";
  };
  "routes/_app.account.tsx": {
    id: "routes/_app.account";
    page: "/account" | "/account/settings" | "/account/billing";
  };
  "routes/_app.account.settings.tsx": {
    id: "routes/_app.account.settings";
    page: "/account/settings";
  };
  "routes/_app.account.billing.tsx": {
    id: "routes/_app.account.billing";
    page: "/account/billing";
  };
  "routes/_app.account._index.tsx": {
    id: "routes/_app.account._index";
    page: "/account";
  };
};